//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorNivel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEVEL4
    {
        public decimal ID_LEVEL4 { get; set; }
        public decimal ID_LEVEL3 { get; set; }
        public string NAME_LEVEL4 { get; set; }
        public string VINCULOPOWERBI { get; set; }
        public string TAG { get; set; }
    
        public virtual LEVEL3 LEVEL3 { get; set; }
    }
}
