//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nivel4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEVEL3
    {
        public LEVEL3()
        {
            this.LEVEL4 = new HashSet<LEVEL4>();
        }
    
        public decimal ID_LEVEL3 { get; set; }
        public decimal ID_LEVEL2 { get; set; }
        public string NAME_LEVEL3 { get; set; }
    
        public virtual LEVEL2 LEVEL2 { get; set; }
        public virtual ICollection<LEVEL4> LEVEL4 { get; set; }
    }
}
