//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nivel4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEVEL2
    {
        public LEVEL2()
        {
            this.LEVEL3 = new HashSet<LEVEL3>();
        }
    
        public decimal ID_LEVEL2 { get; set; }
        public decimal ID_LEVEL1 { get; set; }
        public string NAME_LEVEL2 { get; set; }
    
        public virtual LEVEL1 LEVEL1 { get; set; }
        public virtual ICollection<LEVEL3> LEVEL3 { get; set; }
    }
}
