//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nivel4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LEVEL1> LEVEL1 { get; set; }
        public DbSet<LEVEL2> LEVEL2 { get; set; }
        public DbSet<LEVEL3> LEVEL3 { get; set; }
        public DbSet<LEVEL4> LEVEL4 { get; set; }
        public DbSet<MENU006> MENU006 { get; set; }
    }
}
